package com.nexuspay.common.persistence;

import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import org.springframework.data.domain.Persistable;

import java.util.UUID;

/**
 * Base class for entities whose IDs are assigned by the application rather than
 * generated by the database.
 * <p>
 * This exists to avoid a specific Spring Data JPA trap. {@code save()} decides
 * between {@code persist} and {@code merge} by asking whether the entity is new,
 * and its default answer is "the ID is null". Since we mint UUID v7 IDs
 * ourselves, the ID is <em>never</em> null, so every insert would be treated as
 * an update: a wasted SELECT before each INSERT, and confusing behaviour the
 * moment an entity is genuinely detached.
 * <p>
 * Implementing {@link Persistable} lets the entity answer honestly. The flag
 * starts true and is cleared once the row exists, whether it got there by being
 * persisted or by being loaded.
 */
@MappedSuperclass
public abstract class AssignedIdEntity implements Persistable<UUID> {

    @Transient
    private boolean isNew = true;

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }
}
